routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::softDeletes('users', 'UserController');
    // Route::get('users/trashed', 'UserController@trashed')->name('users.trashed');
    Route::resource('/users','UserController');

});

app/Detail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Detail extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Storage;
use App\Events\UserSaved;

class User extends Authenticatable
{
    use Notifiable,SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function getFullnameAttribute()
    {
        return "{$this->firstname} {$this->middlename} {$this->lastname}";
    }

    public function getMiddleinitialAttribute()
    {
        $names = explode(" ",$this->middlename);
        $initials = "";
        foreach ($names as $name) {
            $initials .= substr($name,0,1).". ";
        }
        return strtoupper($initials);
    }

    public function getAvatarAttribute()
    {
        return asset('/storage/'.$this->photo);
    }

    public function details()
    {
        return $this->hasMany(\App\Detail::class);
    }

    protected $dispatchesEvents = [
        'saved' => UserSaved::class,
    ];

     
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Http\Requests\UserRequest;
use DB;
use Hash;
use Storage;
use Auth;
use App\Services\UserServiceInterface;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    private $userService;
    public function __construct(UserServiceInterface $userService) {
        $this->userService = $userService;
    }

    public function index()
    {
        $users = $this->userService->list();
        return view('user.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        DB::beginTransaction();
        try {
           if($request->hasFile('photo')) $path = $this->userService->upload($request->file('photo'));
           $this->userService->store([
                'prefixname' => $request->prefixname,
                'firstname' => $request->firstname,
                'middlename' => $request->middlename,
                'lastname' => $request->lastname,
                'username' => $request->username,
                'email' => $request->email,
                'photo' => ! isset($path) ?: $path,
                'password' => Hash::make($request->password),
            ]);
            DB::commit();
            return response()->json([
                'message' => 'User successfully created',
            ]);
        } catch (\Throwable $th) {
            DB::rollback();
            return response()->json([
                'message' => 'Something went wrong',
            ]);
        }
       
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('user.show',['user' => $this->userService->find($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('user.edit',['user' => $this->userService->find($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, $id)
    {
        DB::beginTransaction();
        try {
            if($request->hasFile('photo')) $path = $this->userService->upload($request->file('photo'));
            $this->userService->update($id,[
                'prefixname' => $request->prefixname,
                'firstname' => $request->firstname,
                'middlename' => $request->middlename,
                'lastname' => $request->lastname,
                'username' => $request->username,
                'photo' => ! isset($path) ?: $path,
                'email' => $request->email,
            ]);
            DB::commit();
            return response()->json([
                'message' => 'User successfully updated',
            ]);
        } catch (\Throwable $th) {
            DB::rollback();
            return response()->json([
                'message' => 'Something went wrong',
            ]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::beginTransaction();
        try {
            $this->userService->destroy($id);
            DB::commit();
            return back()->with([
                'status' => 'success',
                'message' => 'User successfully deleted'
            ]);
        } catch (\Throwable $th) {
            DB::rollback();
            return back()->with([
                'status' => 'failed',
                'message' => 'Something went wrong'
            ]);
        }
    }

    public function trashed() {
        $users = $this->userService->listTrashed();
        return view('user.index', ['users' => $users,'deleted' => true]);
    }

    public function restore($id) {
        DB::beginTransaction();
        try {
            $this->userService->restore($id);
            DB::commit();
            return back()->with([
                'status' => 'success',
                'message' => 'User successfully restored'
            ]);
        } catch (\Throwable $th) {
            DB::rollback();
            return back()->with([
                'status' => 'failed',
                'message' => 'Something went wrong'
            ]);
        }
    }

    public function delete($id) {
        DB::beginTransaction();
        try {
            $this->userService->delete($id);
            DB::commit();
            return back()->with([
                'status' => 'success',
                'message' => 'User successfully deleted permanently'
            ]);
        } catch (\Throwable $th) {
            DB::rollback();
            return back()->with([
                'status' => 'failed',
                'message' => 'Something went wrong'
            ]);
        }
    }

}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @auth
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('users.index') }}">Active Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('users.trashed') }}">Deleted Users</a>
                        </li>
                        @endauth
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->fullname }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>
@yield('scripts')

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div id="create-user" class="card">
                <div class="card-body">
                    <create-user></create-user>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div id="create-user" class="card">
                <div class="card-body">
                    <create-user :user="{{ $user }}" :avatar="'{{ $user->avatar }}'"></create-user>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <span style="margin-right : 150px">Users</span>
                    <a href="{{ route('users.create') }}"  class="btn btn-primary btn-sm pull-right">Add User</a>
                </div>

                <div class="card-body">
                    <div class="container">
                        @if (session('status'))
                            @if(session('status') == 'success')
                                <div class="alert alert-success">
                                    {{ session('message') }}
                                </div>
                            @else
                                <div class="alert alert-danger">
                                    {{ session('message') }}
                                </div>
                            @endif
                        @endif
                        <table class="table table-bordered">
                            <thead>
                                <td>Name</td>
                                <td>Action</td>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                    </tr>
                                        <td>{{ $user->firstname }}</td>
                                        <td>
                                            @if(isset($deleted))
                                                <form method="POST" action="{{ route('users.restore',$user->id) }}"> 
                                                    @csrf
                                                    @method('PATCH')
                                                    <button type="submit">Restore</button>
                                                </form>
                                                <form method="POST" action="{{ route('users.delete',$user->id) }}"> 
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit">Delete</button>
                                                </form>
                                            @else

                                                <form method="POST" action="{{ route('users.destroy',$user->id) }}"> 
                                                    @csrf
                                                    @method('DELETE')
                                                    <a class="btn btn-primary btn-sm" href="{{ route('users.show',$user->id) }}">View</a> <a class="btn btn-primary btn-sm" href="{{ route('users.edit',$user->id) }}">Edit</a> <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                                </form>
                                            @endif
                                        </td>
                                    <tr>
                                @endforeach
                            </tbody>
                        </table>

                    </div>
                    {{ $users->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div id="create-user" class="card">
                <div class="card-body">
                    <create-user :viewing="true" :user="{{ $user }}" :avatar="'{{ $user->avatar }}'"></create-user>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection